default_platform(:ios)

platform :ios do
  before_all do
    @api_key = app_store_connect_api_key(
      key_id: "7V674759N8",
      issuer_id: "69a6de88-9503-47e3-e053-5b8c7c11a4d1",
      key_filepath: File.join(Dir.pwd, "AuthKey_7V674759N8.p8"),
    )
  end

  desc "Build and upload to App Store"
  lane :release do
    increment_build_number(
      build_number: latest_testflight_build_number(api_key: @api_key) + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    sh("cd ../.. && flutter build ios --release --no-codesign")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "../build/ios",
      output_name: "Sault.ipa",
    )

    upload_to_app_store(
      api_key: @api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number(api_key: @api_key) + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    sh("cd ../.. && flutter build ios --release --no-codesign")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "../build/ios",
      output_name: "Sault.ipa",
    )

    upload_to_testflight(
      api_key: @api_key,
      skip_waiting_for_build_processing: true,
    )
  end
end
